Cleanup functions and aliases (remove some duplicates, move some to bin, unify formatting)

diff --git a/bin/getcertnames b/bin/getcertnames
--- a/bin/getcertnames
+++ b/bin/getcertnames
@@ -4,31 +4,31 @@
 declare tmp domain certText
 
 if [ -z "${1}" ]; then
-  echo "ERROR: No domain specified."
-  return 1
+    echo "ERROR: No domain specified."
+    return 1
 fi
 
 domain="${1}"
 echo "Testing ${domain}…"
 echo # newline
 
-tmp=$(echo -e "GET / HTTP/1.0\nEOT" |
-  openssl s_client -connect "${domain}:443" 2>&1)
+tmp=$(echo -e "GET / HTTP/1.0\nEOT" \
+    | openssl s_client -connect "${domain}:443" 2>&1)
 
 if [[ "${tmp}" = *"-----BEGIN CERTIFICATE-----"* ]]; then
-  certText=$(echo "${tmp}" |
-    openssl x509 -text -certopt "no_header, no_serial, no_version, \
+    certText=$(echo "${tmp}" \
+        | openssl x509 -text -certopt "no_header, no_serial, no_version, \
     no_signame, no_validity, no_issuer, no_pubkey, no_sigdump, no_aux")
-  echo "Common Name:"
-  echo # newline
-  echo "${certText}" | grep "Subject:" | sed -e "s/^.*CN=//"
-  echo # newline
-  echo "Subject Alternative Name(s):"
-  echo # newline
-  echo "${certText}" | grep -A 1 "Subject Alternative Name:" |
-    sed -e "2s/DNS://g" -e "s/ //g" | tr "," "\n" | tail -n +2
-  exit 0
+    echo "Common Name:"
+    echo # newline
+    echo "${certText}" | grep "Subject:" | sed -e "s/^.*CN=//"
+    echo # newline
+    echo "Subject Alternative Name(s):"
+    echo # newline
+    echo "${certText}" | grep -A 1 "Subject Alternative Name:" \
+        | sed -e "2s/DNS://g" -e "s/ //g" | tr "," "\n" | tail -n +2
+    exit 0
 else
-  echo "ERROR: Certificate not found."
-  exit 1
+    echo "ERROR: Certificate not found."
+    exit 1
 fi
